### ISSUE TITLE
Unable to install the package Discord.Addons.SimplePermissions 0.7.13-a

### ISSUE THREAD

**Issue by raxixor** [Joe4evr/Discord.Addons#3]
Could not install package 'Discord.Addons.SimplePermissions 0.7.13-a'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by Joe4evr** [comment]
Target .NET 4.6+ or .NET Core 1.0.
