### ISSUE TITLE
Discord.SimplePermissions issue

### ISSUE THREAD

**Issue by raxixor** [Joe4evr/Discord.Addons#4]
An error with the `await commandService.AddPermissionsService(client, configstore, map);` bit of code, as it doesn't work for me, when translated to the way I have it set up.

Image of my problem provided.
![image](https://cloud.githubusercontent.com/assets/1861988/22204105/e38838a0-e178-11e6-9f25-2acad19e9677.png)

**Comment by Joe4evr** [comment]
Are you on the latest version? The extension method was added in `0.7.13-a`

**Comment by raxixor** [comment]
Yes, I am on `0.7.13-a`.
![image](https://cloud.githubusercontent.com/assets/1861988/22205423/7d2f9b46-e17f-11e6-915d-92c353e2958a.png)

**Comment by Joe4evr** [comment]
Weird. Can you update to `0.7.15-a` which I pushed just earlier?

**Comment by raxixor** [comment]
It works now. Thanks.
